databases:
  - name: rod-db
    databaseName: rod-db
    user: rod_db_user

services:
  - type: web
    name: Budget-app-rod
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rod-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false